---
group:
subGroup: pregnancy_data_&_medical_history
fields:

  - template: "Gravida: {gravidity}"
    relevance: "gravidity != ''"
    isRedFont: "gravidity >= 5"

  - template: "Para: {parity}"
    relevance: "parity != ''"
    isRedFont: "parity >= 5"

  - template: "Last menstrual period date: {lmp_unknown} {lmp}"
    relevance: "lmp_unknown != '' || lmp != ''"

  - template: "Gestation age: {gest_age} "
    relevance: "gest_age != ''"

  - template: "Onset of Labour: {onset_labour}{onset_labour_time}"
    relevance: "onset_labour != '' || onset_labour_time != ''"

  - template: "Any past pregnancy problems?: {previous_complications}{previous_complications_other}"
    relevance: "previous_complications != '' || previous_complications_other != ''"

  - template: "Family medical history: {family_history}{family_history_other}"
    relevance: "family_history != '' || family_history_other != ''"

  - template: "How many does of TDV did the mother receive?: {mother_tdv_doses}"
    relevance: "mother_tdv_doses != ''"

  - template: "Children Protected at birth (PAB): {protected_at_birth}"
    relevance: "protected_at_birth != ''"

---
subGroup: delivery_&_outcome_details
fields:

  - template: "Date of delivery: {delivery_date}"
    relevance: "delivery_date != ''"

  - template: "Place of delivery: {delivery_place}"
    relevance: "delivery_place != ''"

  - template: "Staff conducting the delivery: {delivery_person}{delivery_person_other}"
    relevance: "delivery_person != '' || delivery_person_other != ''"

  - template: "Mode of delivery: {delivery_mode}{delivery_mode_other}"
    relevance: "delivery_mode != '' || delivery_mode_other != ''"

  - template: "Obstetric complications: {obstretic_complications}{obstretic_complications_other}"
    relevance: "obstretic_complications != '' || obstretic_complications_other != ''"
    isRedFont: "obstretic_complications_other != 'None'"

  - template: "Obstetric care: {obstretic_care}{obstretic_care_other}"
    relevance: "obstretic_care != '' || obstretic_care_other != ''"

  - template: "Referred out: {referred_out}"
    relevance: "referred_out != ''"

  - template: "Vitamin A: {vit_a}"
    relevance: "vit_a != ''"

  - template: "Discharges status: {discharge_status}"
    relevance: "discharge_status != ''"

---
subGroup: hiv_status_&_treatment
fields:

  - template: "HIV status at registration: {hiv_status}"
    relevance: "hiv_status != ''"
    isRedFont: "hiv_status == 'positive'"

  - template: "Is the woman on ART treatment?: {on_art_treatment}"
    relevance: "on_art_treatment != ''"

---
subGroup: live_births
fields:

---
subGroup: stillbirths
fields:




